apiVersion: cluster.x-k8s.io/v1alpha3
kind: Cluster
metadata:
  name: ${ CLUSTER_NAME }
  namespace: ${ NAMESPACE }
spec:
  clusterNetwork:
    services:
      cidrBlocks: [${ SERVICE_CIDR }]
    pods:
      cidrBlocks: [${ POD_CIDR }]
  infrastructureRef:
{% if CAPM3_VERSION == "v1alpha4" %}
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
{% else %}
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
{% endif %}
    kind: Metal3Cluster
    name: ${ CLUSTER_NAME }
  controlPlaneRef:
    kind: KubeadmControlPlane
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    name: ${ CLUSTER_NAME }
---
{% if CAPM3_VERSION == "v1alpha4" %}
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
{% else %}
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha4
{% endif %}
kind: Metal3Cluster
metadata:
  name: ${ CLUSTER_NAME }
  namespace: ${ NAMESPACE }
spec:
  controlPlaneEndpoint:
    host: ${ API_ENDPOINT_HOST }
    port: ${ API_ENDPOINT_PORT }
  noCloudProvider: true
---
apiVersion: ipam.metal3.io/v1alpha1
kind: IPPool
metadata:
  name: provisioning-pool
  namespace: ${ NAMESPACE }
spec:
  clusterName: ${ CLUSTER_NAME }
  namePrefix: ${ CLUSTER_NAME }-prov
  pools:
    - start: ${ PROVISIONING_POOL_RANGE_START }
      end: ${ PROVISIONING_POOL_RANGE_END }
  prefix: ${ PROVISIONING_CIDR }
{% if IP_STACK == 'v4' or IP_STACK == 'v4v6' %}
---
apiVersion: ipam.metal3.io/v1alpha1
kind: IPPool
metadata:
  name: baremetalv4-pool
  namespace: ${ NAMESPACE }
spec:
  clusterName: ${ CLUSTER_NAME }
  namePrefix: ${ CLUSTER_NAME }-bmv4
  pools:
    - start: ${ BAREMETALV4_POOL_RANGE_START }
      end: ${ BAREMETALV4_POOL_RANGE_END }
  prefix: ${ EXTERNAL_SUBNET_V4_PREFIX }
  gateway: ${ EXTERNAL_SUBNET_V4_HOST }
{% endif %}
{% if IP_STACK == 'v6' or IP_STACK == 'v4v6' %}
---
apiVersion: ipam.metal3.io/v1alpha1
kind: IPPool
metadata:
  name: baremetalv6-pool
  namespace: ${ NAMESPACE }
spec:
  clusterName: ${ CLUSTER_NAME }
  namePrefix: ${ CLUSTER_NAME }-bmv6
  pools:
    - start: ${ BAREMETALV6_POOL_RANGE_START }
      end: ${ BAREMETALV6_POOL_RANGE_END }
  prefix: ${ EXTERNAL_SUBNET_V6_PREFIX }
  gateway: ${ EXTERNAL_SUBNET_V6_HOST }
{% endif %}