kind: KubeadmControlPlane
apiVersion: controlplane.cluster.x-k8s.io/{{ CAPI_VERSION }}
metadata:
  name: ${ CLUSTER_NAME }
  namespace: ${ NAMESPACE }
spec:
  rolloutStrategy:
    rollingUpdate:
      maxSurge: ${ MAX_SURGE_VALUE }
  replicas: ${ NUM_OF_MASTER_REPLICAS }
  version: ${ KUBERNETES_VERSION }
{% if CAPI_VERSION == "v1alpha3" %}
  nodeDrainTimeout: ${ NODE_DRAIN_TIMEOUT }
  infrastructureTemplate:
    kind: Metal3MachineTemplate
    apiVersion: infrastructure.cluster.x-k8s.io/{{ CAPM3_VERSION }}
    name: ${ CLUSTER_NAME }-controlplane
{% else %}
  machineTemplate:
    nodeDrainTimeout: ${ NODE_DRAIN_TIMEOUT }
    infrastructureRef:
      kind: Metal3MachineTemplate
      apiVersion: infrastructure.cluster.x-k8s.io/{{ CAPM3_VERSION }}
      name: ${ CLUSTER_NAME }-controlplane
{% endif %}
  kubeadmConfigSpec:
    clusterConfiguration: {}
    joinConfiguration:
      controlPlane: {}
      nodeRegistration:
        name: "{{ '{{ ds.meta_data.name }}' }}"
        kubeletExtraArgs:
          node-labels: "metal3.io/uuid={{ '{{ ds.meta_data.uuid }}' }}"
          provider-id: "metal3://{{ '{{ ds.meta_data.uuid }}' }}"
          feature-gates: "AllAlpha=false,RunAsGroup=true"
          container-runtime: "remote"
          cgroup-driver: "systemd"
          container-runtime-endpoint: "unix:///var/run/crio/crio.sock"
          runtime-request-timeout: "5m"
    initConfiguration:
      nodeRegistration:
        name: "{{ '{{ ds.meta_data.name }}' }}"
        kubeletExtraArgs:
          node-labels: "metal3.io/uuid={{ '{{ ds.meta_data.uuid }}' }}"
          provider-id: "metal3://{{ '{{ ds.meta_data.uuid }}' }}"
          feature-gates: "AllAlpha=false,RunAsGroup=true"
          container-runtime: "remote"
          cgroup-driver: "systemd"
          container-runtime-endpoint: "unix:///var/run/crio/crio.sock"
          runtime-request-timeout: "5m"
    users:
    - name: {{ IMAGE_USERNAME }}
      sudo: "ALL=(ALL) NOPASSWD:ALL"
      sshAuthorizedKeys:
      - {{ SSH_PUB_KEY_CONTENT }}
{% filter indent(width=4, first=True) %}
{% include "cluster-template-controlplane-kubeadm-config-%s.yaml" % (IMAGE_OS | lower) %}
{% endfilter %}

---
apiVersion: infrastructure.cluster.x-k8s.io/{{ CAPM3_VERSION }}
kind: Metal3MachineTemplate
metadata:
  name: ${ CLUSTER_NAME }-controlplane
  namespace: ${ NAMESPACE }
spec:
  template:
    spec:
      image:
        url: {{ IMAGE_URL }}
        checksum: {{ IMAGE_CHECKSUM }}
        checksumType: {{ IMAGE_CHECKSUM_TYPE }}
        format: {{ IMAGE_FORMAT }}
      dataTemplate:
        name: ${ CLUSTER_NAME }-controlplane-template
---
apiVersion: infrastructure.cluster.x-k8s.io/{{ CAPM3_VERSION }}
kind: Metal3DataTemplate
metadata:
  name: ${ CLUSTER_NAME }-controlplane-template
spec:
  clusterName: ${ CLUSTER_NAME }
  metaData:
    objectNames:
      - key: name
        object: machine
      - key: local-hostname
        object: machine
      - key: local_hostname
        object: machine
    ipAddressesFromIPPool:
      - key: provisioningIP
        name: provisioning-pool
    prefixesFromIPPool:
      - key: provisioningCIDR
        name: provisioning-pool
  networkData:
    links:
      ethernets:
        - type: phy
          id: enp1s0
          macAddress:
            fromHostInterface: enp1s0
        - type: phy
          id: enp2s0
          macAddress:
            fromHostInterface: enp2s0
    networks:
{% if IP_STACK == 'v4' or IP_STACK == 'v4v6' %}
      ipv4:
        - id: baremetalv4
          link: enp2s0
          ipAddressFromIPPool: baremetalv4-pool
          routes:
            - network: 0.0.0.0
              prefix: 0
              gateway:
                fromIPPool: baremetalv4-pool
{% endif %}
{% if IP_STACK == 'v6' or IP_STACK == 'v4v6'%}
      ipv6:
        - id: baremetalv6
          link: enp2s0
          ipAddressFromIPPool: baremetalv6-pool
          routes:
            - network: 0::0
              prefix: 0
              gateway:
                fromIPPool: baremetalv6-pool
{% endif %}
    services:
      dns:
{% if IP_STACK == 'v4' or IP_STACK == 'v4v6' %}
        - 8.8.8.8
{% endif %}
{% if IP_STACK == 'v6' or IP_STACK == 'v4v6' %}
        - 2001:4860:4860::8888
{% endif %}
