apiVersion: cluster.x-k8s.io/{{ CAPI_VERSION }}
kind: MachineDeployment
metadata:
  name: ${ CLUSTER_NAME }
  namespace: ${ NAMESPACE }
  labels:
    cluster.x-k8s.io/cluster-name: ${ CLUSTER_NAME }
    nodepool: nodepool-0
spec:
  clusterName: ${ CLUSTER_NAME }
  replicas: ${ NUM_OF_WORKER_REPLICAS }
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: ${ CLUSTER_NAME }
      nodepool: nodepool-0
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: ${ CLUSTER_NAME }
        nodepool: nodepool-0
    spec:
{% if CAPI_VERSION == "v1alpha3" %}
      nodeDrainTimeout: ${ NODE_DRAIN_TIMEOUT }
{% else %}
      machineTemplate:
        nodeDrainTimeout: ${ NODE_DRAIN_TIMEOUT }
{% endif %}
      clusterName: ${ CLUSTER_NAME }
      version: ${ KUBERNETES_VERSION }
      bootstrap:
        configRef:
          name: ${ CLUSTER_NAME }-workers
          apiVersion: bootstrap.cluster.x-k8s.io/{{ CAPI_VERSION }}
          kind: KubeadmConfigTemplate
      infrastructureRef:
        name: ${ CLUSTER_NAME }-workers
        apiVersion: infrastructure.cluster.x-k8s.io/{{ CAPM3_VERSION }}
        kind: Metal3MachineTemplate
---
apiVersion: infrastructure.cluster.x-k8s.io/{{ CAPM3_VERSION }}
kind: Metal3MachineTemplate
metadata:
  name: ${ CLUSTER_NAME }-workers
  namespace: ${ NAMESPACE }
spec:
  template:
    spec:
      image:
        url: {{ IMAGE_URL }}
        checksum: {{ IMAGE_CHECKSUM }}
        checksumType: {{ IMAGE_CHECKSUM_TYPE }}
        format: {{ IMAGE_FORMAT }}
      dataTemplate:
        name: ${ CLUSTER_NAME }-workers-template
---
apiVersion: infrastructure.cluster.x-k8s.io/{{ CAPM3_VERSION }}
kind: Metal3DataTemplate
metadata:
  name: ${ CLUSTER_NAME }-workers-template
  namespace: ${ NAMESPACE }
spec:
  clusterName: ${ CLUSTER_NAME }
  metaData:
    objectNames:
      - key: name
        object: machine
      - key: local-hostname
        object: machine
      - key: local_hostname
        object: machine
    ipAddressesFromIPPool:
      - key: provisioningIP
        name: provisioning-pool
    prefixesFromIPPool:
      - key: provisioningCIDR
        name: provisioning-pool
  networkData:
    links:
      ethernets:
        - type: phy
          id: enp1s0
          macAddress:
            fromHostInterface: enp1s0
        - type: phy
          id: enp2s0
          macAddress:
            fromHostInterface: enp2s0
    networks:
{% if IP_STACK == 'v4' or IP_STACK == 'v4v6' %}
      ipv4:
        - id: baremetalv4
          link: enp2s0
          ipAddressFromIPPool: baremetalv4-pool
          routes:
            - network: 0.0.0.0
              prefix: 0
              gateway:
                fromIPPool: baremetalv4-pool
{% endif %}
{% if IP_STACK == 'v6' or IP_STACK == 'v4v6'%}
      ipv6:
        - id: baremetalv6
          link: enp2s0
          ipAddressFromIPPool: baremetalv6-pool
          routes:
            - network: 0::0
              prefix: 0
              gateway:
                fromIPPool: baremetalv6-pool
{% endif %}
    services:
      dns:
{% if IP_STACK == 'v4' or IP_STACK == 'v4v6' %}
        - 8.8.8.8
{% endif %}
{% if IP_STACK == 'v6' or IP_STACK == 'v4v6' %}
        - 2001:4860:4860::8888
{% endif %}
---
apiVersion: bootstrap.cluster.x-k8s.io/{{ CAPI_VERSION }}
kind: KubeadmConfigTemplate
metadata:
  name: ${ CLUSTER_NAME }-workers
  namespace: ${ NAMESPACE }
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          name: "{{ '{{ ds.meta_data.name }}' }}"
          kubeletExtraArgs:
            node-labels: "metal3.io/uuid={{ '{{ ds.meta_data.uuid }}' }}"
            provider-id: "metal3://{{ '{{ ds.meta_data.uuid }}' }}"
            feature-gates: "AllAlpha=false"
            container-runtime: "remote"
            cgroup-driver: "systemd"
            container-runtime-endpoint: "unix:///var/run/crio/crio.sock"
            runtime-request-timeout: "5m"
      users:
      - name: {{ IMAGE_USERNAME }}
        sudo: "ALL=(ALL) NOPASSWD:ALL"
        sshAuthorizedKeys:
        - {{ SSH_PUB_KEY_CONTENT }}
{% filter indent(width=6, first=True) %}
{% include "cluster-template-workers-kubeadm-config-%s.yaml" % (IMAGE_OS | lower) %}
{% endfilter %}
