use_firewalld: true
baremetal_interface: baremetal
provisioning_interface: provisioning
external_subnet_v4: "{{ lookup('env', 'EXTERNAL_SUBNET_V4') | default('192.168.111.0/24', true) }}"
vbmc_port_range: "6230:6235"
sushy_port: 8000
firewall_rule_state: present
ironic_ports:
  - "6180"
  - "5050"
  - "6385"
  - "9999"
  - "80"
provisioning_host_ports:
  # Caching HTTP Server
  - "80"
  # Container image registry
  - "5000"
  # DNS for registry naming resolution
  - "53"
pxe_udp_ports:
  # Multicast DNS
  - "5353"
  # DHCP
  - "67"
  - "68"
  # DHCPv6
  - "546"
  - "547"
  # TFTP
  - "69"
ironic_keepalived_proto:
  - "112"
  - "icmp"

EPHEMERAL_CLUSTER: "{{ lookup('env', 'EPHEMERAL_CLUSTER') | default('kind', true)}}"

