use_firewalld: "{{ lookup('env', 'USE_FIREWALLD') | default('true', true) }}"
external_interface: external
provisioning_interface: provisioning
bare_metal_provisioner_interface: "{{ lookup('env', 'BARE_METAL_PROVISIONER_INTERFACE') | default('ironicendpoint', true) }}"
# Set external subnet based on the used protocol
ip_stack: "{{ lookup('env', 'IP_STACK') | default('v4', true) }}"
external_subnet_v4: "{{ lookup('env', 'EXTERNAL_SUBNET_V4') | default('192.168.111.0/24', true) }}"
external_subnet_v6: "{{ lookup('env', 'EXTERNAL_SUBNET_V6') | default('fd55::/64', true) }}"
# Bare metal provisioner subnet can also be IPv6, set in lib/network.sh line 48
bare_metal_provisioner_subnet: "{{ lookup('env', 'BARE_METAL_PROVISIONER_NETWORK') | default('172.22.0.0/24', true) }}"
# These values come from kind defaults.
kind_subnet: "{{ '172.18.0.0/24' if ip_stack == 'v4' else 'fc00:f853:ccd:e793::/64' }}"
registry_port: "{{ lookup('env', 'REGISTRY_PORT') | default('5000', true) }}"
http_port: "{{ lookup('env', 'HTTP_PORT') | default('6180', true) }}"
ironic_inspector_port: "{{ lookup('env', 'IRONIC_INSPECTOR_PORT') | default('5050', true) }}"
ironic_api_port: "{{ lookup('env', 'IRONIC_API_PORT') | default('6385', true) }}"
vbmc_port_range: "6230:6235"
sushy_port: 8000
cluster_api_port: "{{ lookup('env', 'CLUSTER_APIENDPOINT_PORT') | default('6443', true) }}"
firewall_rule_state: present
ironic_ports:
  - "{{ http_port }}"
  - "443"
  - "{{ ironic_inspector_port }}"
  - "{{ ironic_api_port }}"
  - "9999"
  - "80"
vm_host_ports:
  # Caching HTTP Server
  - "80"
  # Container image registry
  - "{{ registry_port }}"
  # DNS for registry naming resolution
  - "53"
  - "443"
pxe_udp_ports:
  # Multicast DNS
  - "5353"
  # DHCP
  - "67"
  - "68"
  # DHCPv6
  - "546"
  - "547"
  # TFTP
  - "69"
ironic_keepalived_proto:
  - "112"
  - "icmp"

EPHEMERAL_CLUSTER: "{{ lookup('env', 'EPHEMERAL_CLUSTER') | default('kind', true)}}"
