---
  - name: Check IMAGE_OS CentOS
    block:
      - name: Get the facts about local CentOS image
        stat:
          path: "{{ IRONIC_IMAGE_DIR }}/{{ RAW_IMAGE_NAME_CENTOS }}"
        register: image_path_centos

      - debug:
          msg: "Local image of CentOS is found"
        when:
          - image_path_centos.stat.exists == True

      - name: Download CentOS image.
        block:
          - debug:
              msg: "Local image of CentOS is not found, starting to download"

          - name: Verify specific centos image containing newer version of cloud-init is downloaded
            get_url:
              url: "{{ IMAGE_LOCATION_CENTOS }}/{{ IMAGE_NAME_CENTOS }}"
              dest: "{{ IRONIC_IMAGE_DIR }}/{{ IMAGE_NAME_CENTOS }}"
              mode: 0664

          - name: Create Centos raw image
            shell: |
              qemu-img convert -O raw "{{ IRONIC_IMAGE_DIR }}/{{IMAGE_NAME_CENTOS}}" "{{ IRONIC_IMAGE_DIR }}/{{RAW_IMAGE_NAME_CENTOS}}"

          - name: Calculate md5sum of the centos image
            stat:
              path: "{{ IRONIC_IMAGE_DIR }}/{{ RAW_IMAGE_NAME_CENTOS }}"
              checksum_algorithm: md5
            register: centos_md5

          - name: Create the md5sum file
            copy:
              content: |
                {{ centos_md5.stat.checksum }}

              dest: "{{ IRONIC_IMAGE_DIR }}/{{ RAW_IMAGE_NAME_CENTOS }}.md5sum"
              mode: 0664
        when:
          - image_path_centos.stat.exists == False
    when:
      - IMAGE_OS == "Centos"

  - name: Check IMAGE_OS Ubuntu
    block:
      - name: Get the facts about local Ubuntu image
        stat:
          path: "{{ IRONIC_IMAGE_DIR }}/{{ RAW_IMAGE_NAME }}"
        register: image_path_ubuntu

      - debug:
          msg: "Local image of Ubuntu is found"
        when:
          - image_path_ubuntu.stat.exists == True

      - name: Download Ubuntu image.
        block:
          - debug:
              msg: "Local image of Ubuntu is not found, starting to download"

          - name: Verify specific Ubuntu image containing newer version of cloud-init is downloaded
            get_url:
              url: "{{ IMAGE_LOCATION }}/{{ IMAGE_NAME }}"
              dest: "{{ IRONIC_IMAGE_DIR }}/{{ IMAGE_NAME }}"
              mode: 0664

          - name: Create Ubuntu raw image
            shell: |
              qemu-img convert -O raw "{{ IRONIC_IMAGE_DIR }}/{{IMAGE_NAME}}" "{{ IRONIC_IMAGE_DIR }}/{{RAW_IMAGE_NAME}}"

          - name: Calculate md5sum of the Ubuntu image
            stat:
              path: "{{ IRONIC_IMAGE_DIR }}/{{ RAW_IMAGE_NAME }}"
              checksum_algorithm: md5
            register: ubuntu_md5

          - name: Create the md5sum file
            copy:
              content: |
                {{ ubuntu_md5.stat.checksum }}

              dest: "{{ IRONIC_IMAGE_DIR }}/{{ RAW_IMAGE_NAME }}.md5sum"
              mode: 0664
        when:
          - image_path_ubuntu.stat.exists == False
    when:
      - IMAGE_OS == "Ubuntu"
