---
  - name: Get BMH facts
    k8s_info:
      api_version: metal3.io/v1alpha1
      kind: BareMetalHost
      namespace: "{{ NAMESPACE }}"
    register: bmhs # A list of BMHs

  - name: Set fact for NIC names for the first BMH found
    set_fact:
      # We assume that the NIC names for different nodes are the same.
      bmh_nic_names: "{{ bmhs['resources'] | first | bmh_nic_names }}"

  - name: Create a temporary manifest directory if it does not exist
    file:
      path: "{{ TEMP_GEN_DIR }}"
      state: directory
      mode: '0755'

  - name: Deploy clusterctl variables to clusterctl config
    template:
      src: clusterctl-vars.yaml
      dest: "{{ HOME }}/.cluster-api/clusterctl.yaml"

  - name: Generate clusterctl cluster template
    template:
      src: "{{ CRS_PATH }}/cluster-template-{{ item }}.yaml"
      dest: "{{ HOME }}/.cluster-api/overrides/infrastructure-metal3/{{ CAPM3RELEASE }}/cluster-template-{{ item }}.yaml"
    with_items:
      - cluster
      - controlplane
      - workers

  - name: Generate templates
    vars:
      clusterctl_var: "{{ 'generate' if CAPI_VERSION == 'v1beta1' else 'config' }}"
    shell: >
      clusterctl {{ clusterctl_var }} cluster {{ CLUSTER_NAME }}
      --from {{ HOME }}/.cluster-api/overrides/infrastructure-metal3/{{ CAPM3RELEASE }}/cluster-template-{{ item }}.yaml
      --kubernetes-version {{ KUBERNETES_VERSION }}
      --control-plane-machine-count={{ NUM_OF_MASTER_REPLICAS }}
      --worker-machine-count={{ NUM_OF_WORKER_REPLICAS }}
      --target-namespace={{ NAMESPACE }} > {{ TEMP_GEN_DIR }}/{{ CAPM3_VERSION }}_{{ item }}_{{ IMAGE_OS|lower }}.yaml
    with_items:
      - cluster
      - controlplane
      - workers
