---
- name: Generate templates
  include_tasks: generate_templates.yml

- name: Download image for deployment
  include_tasks: download_image.yml
  when: v1aX_integration_test_action in image_download_actions

- name: Test inspection API
  include_tasks: inspection.yml
  when: v1aX_integration_test_action in inspection_action

- name: Provision cluster
  kubernetes.core.k8s:
    state: present
    src: "{{ TEMP_GEN_DIR }}/{{ CAPM3_VERSION }}_cluster_{{ IMAGE_OS|lower }}.yaml"
    namespace: "{{ NAMESPACE }}"
  when: v1aX_integration_test_action in provision_cluster_actions

- name: Create control plane
  kubernetes.core.k8s:
    state: present
    src: "{{ TEMP_GEN_DIR }}/{{ CAPM3_VERSION }}_controlplane_{{ IMAGE_OS|lower }}.yaml"
    namespace: "{{ NAMESPACE }}"
  when: v1aX_integration_test_action in provision_controlplane_actions

- name: Create worker nodes
  kubernetes.core.k8s:
    state: present
    src: "{{ TEMP_GEN_DIR }}/{{ CAPM3_VERSION }}_workers_{{ IMAGE_OS|lower }}.yaml"
    namespace: "{{ NAMESPACE }}"
  when: v1aX_integration_test_action in provision_workers_actions

- name: verify deployment
  include_tasks: verify.yml
  when: v1aX_integration_test_action in verify_actions

- name: pivot
  include_tasks: move.yml
  when: v1aX_integration_test_action in pivot_actions

- name: Upgrade cluster
  include_tasks: upgrade.yml
  when: v1aX_integration_test_action == "upgrading"

- name: post pivot operations
  include_tasks: post_pivot.yml
  when: v1aX_integration_test_action == "post_pivot"

- name: repivot
  include_tasks: move_back.yml
  when: v1aX_integration_test_action in repivot_actions

- name: Deprovision worker nodes
  kubernetes.core.k8s:
    state: absent
    src: "{{ TEMP_GEN_DIR }}/{{ CAPM3_VERSION }}_workers_{{ IMAGE_OS|lower }}.yaml"
    namespace: "{{ NAMESPACE }}"
  ignore_errors: yes
  when: v1aX_integration_test_action in deprovision_workers_actions

- name: Deprovision control plane
  kubernetes.core.k8s:
    state: absent
    src: "{{ TEMP_GEN_DIR }}/{{ CAPM3_VERSION }}_controlplane_{{ IMAGE_OS|lower }}.yaml"
    namespace: "{{ NAMESPACE }}"
  ignore_errors: yes
  when: v1aX_integration_test_action in deprovision_controlplane_actions

- name: Deprovision cluster
  kubernetes.core.k8s:
    state: absent
    src: "{{ TEMP_GEN_DIR }}/{{ CAPM3_VERSION }}_cluster_{{ IMAGE_OS|lower }}.yaml"
    namespace: "{{ NAMESPACE }}"
  ignore_errors: yes
  when: v1aX_integration_test_action in deprovision_cluster_actions

- name: Cleanup deployment
  include_tasks: cleanup.yml
  when: v1aX_integration_test_action in cleanup_actions

- name: Node remediation
  include_tasks: remediation.yml
  when: v1aX_integration_test_action == "remediation"

- name: Node reuse
  include_tasks: node_reuse.yml
  when: v1aX_integration_test_action == "node_reuse"
