---
- name: Install openshift client in CentOS 8 using pip3
  pip:
    executable: "pip3"
    name: openshift
    state: present
  become: true
  become_user: root
  when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == '8'

- name: Install openshift client in CentOS 7 using pip
  pip:
    executable: "pip"
    name: openshift
    state: present
  become: true
  become_user: root
  when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == '7'

- name: "Generate templates for v1alpha3"
  include: generate_templates.yml

- name: download image for deployment
  include: download_image.yml
  when: v1aX_integration_test_action in image_download_actions

- name: Provision cluster
  k8s:
    state: present
    src: "{{ TEMP_GEN_DIR }}/{{ CAPM3_VERSION }}_cluster_{{ IMAGE_OS|lower }}.yaml"
    namespace: "{{ NAMESPACE }}"
  when: v1aX_integration_test_action in provision_cluster_actions

- name: Create control plane
  k8s:
    state: present
    src: "{{ TEMP_GEN_DIR }}/{{ CAPM3_VERSION }}_controlplane_{{ IMAGE_OS|lower }}.yaml"
    namespace: "{{ NAMESPACE }}"
  when: v1aX_integration_test_action in provision_controlplane_actions

- name: Create worker nodes
  k8s:
    state: present
    src: "{{ TEMP_GEN_DIR }}/{{ CAPM3_VERSION }}_workers_{{ IMAGE_OS|lower }}.yaml"
    namespace: "{{ NAMESPACE }}"
  when: v1aX_integration_test_action in provision_workers_actions

- name: verify deployment
  include: verify.yml
  when: v1aX_integration_test_action in verify_actions

- name: pivot
  include: move.yml
  when: v1aX_integration_test_action == "pivoting"

- name: Fetch cluster manifests
  shell: "{{ MANIFESTS_DIR }}/fetch_manifests.sh"
  when: v1aX_integration_test_action == "ci_test"

- name: Deprovision cluster
  k8s:
    state: absent
    src: "{{ TEMP_GEN_DIR }}/{{ CAPM3_VERSION }}_cluster_{{ IMAGE_OS|lower }}.yaml"
    namespace: "{{ NAMESPACE }}"
  ignore_errors: yes
  when: v1aX_integration_test_action in deprovision_cluster_actions

- name: Deprovision control plane
  k8s:
    state: absent
    src: "{{ TEMP_GEN_DIR }}/{{ CAPM3_VERSION }}_controlplane_{{ IMAGE_OS|lower }}.yaml"
    namespace: "{{ NAMESPACE }}"
  ignore_errors: yes
  when: v1aX_integration_test_action in deprovision_controlplane_actions

- name: Deprovision worker nodes
  k8s:
    state: absent
    src: "{{ TEMP_GEN_DIR }}/{{ CAPM3_VERSION }}_workers_{{ IMAGE_OS|lower }}.yaml"
    namespace: "{{ NAMESPACE }}"
  ignore_errors: yes
  when: v1aX_integration_test_action in deprovision_workers_actions

- name: Cleanup deployment
  include: cleanup.yml
  when: v1aX_integration_test_action in cleanup_actions

- name: Node remediation
  include: remediation.yml
  when: v1aX_integration_test_action == "remediation"